# Generated by Django 4.1 on 2022-09-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='sent',
            field=models.DateTimeField(null=True),
        ),
    ]
