# Generated by Django 4.1 on 2022-10-10 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_class_name'),
        ('users', '0008_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sublevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sublevel'),
        ),
    ]
