# Generated by Django 4.1 on 2022-11-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_name_topic_note'),
        ('users', '0012_alter_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.phonenumber'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sublevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sublevel'),
        ),
    ]
