# Generated by Django 4.1 on 2022-10-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0023_rename_name_topic_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('sublevel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.sublevel')),
                ('duration', models.PositiveIntegerField(default=7)),
                ('duration_period', models.CharField(choices=[('1M', '1 Month'), ('3M', '3 Months'), ('12M', '12 Months')], default='Day', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            bases=('api.sublevel',),
        ),
    ]
