# Generated by Django 4.1 on 2022-10-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_name_topic_note'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_period', models.CharField(choices=[('1M', '1 Month'), ('3M', '3 Months'), ('12M', '12 Months')], default='1M', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level')),
                ('sublevel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sublevel')),
            ],
        ),
        migrations.DeleteModel(
            name='plan',
        ),
    ]
