# Generated by Django 4.1 on 2022-10-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_name_topic_note'),
        ('payment', '0002_paymentplan_delete_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentPlan',
            new_name='Plan',
        ),
    ]
