# Generated by Django 4.1 on 2022-09-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(choices=[('jss1', 'Junior Secondary School 1'), ('jss2', 'Junior Secondary School 2'), ('jss3', 'Junior Secondary School 3')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('jss', 'jss'), ('sss', 'sss'), ('UTME', 'UTME'), ('IE', 'IE')], max_length=50),
        ),
    ]
