# Generated by Django 4.1 on 2022-10-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_level_name_class_subject_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='classes',
        ),
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(null=True, to='api.class'),
        ),
    ]
