# Generated by Django 4.1 on 2022-10-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_subject_classes_subject_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='classes',
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(to='api.subject'),
        ),
    ]
