# Generated by Django 4.1 on 2022-10-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('jss', 'Junior Secondary School'), ('sss', 'Senior Secondary School'), ('UTME', 'UTME/PUTME'), ('IE', 'International Exams')], max_length=100),
        ),
    ]
