# Generated by Django 4.1 on 2022-10-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('JSS', 'Junior Secondary School'), ('SSS', 'Senior Secondary School'), ('UTME', 'UTME/PUTME'), ('IE', 'International Exams')], max_length=100),
        ),
    ]
