# Generated by Django 4.1 on 2022-10-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_level_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Topic',
            new_name='Lesson',
        ),
    ]
