# Generated by Django 4.1 on 2022-10-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_lesson_body_alter_topic_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='url',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
