# Generated by Django 4.1 on 2022-10-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_topic_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='url',
            new_name='videoUrl',
        ),
        migrations.AddField(
            model_name='topic',
            name='thumbnailUrl',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
