# Generated by Django 4.1 on 2022-10-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_title_topic_name_rename_url_topic_videourl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='note',
        ),
    ]
