# Generated by Django 4.1 on 2022-11-08 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_name_topic_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublevel',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublevel', to='api.level'),
        ),
    ]
