# Generated by Django 4.1 on 2023-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_sublevel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='colour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
