# Generated by Django 4.1 on 2023-04-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_course_colour_lesson_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='colour',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('orange', 'orange'), ('purple', 'purple')], max_length=50, null=True),
        ),
    ]
